version: "3"
services:
  front_end:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./.next:/usr/src/app/.next
    ports:
      - "3000:3000"